# file      : buildfile
# license   : PostgreSQL License; see accompanying COPYRIGHT file

./: {*/ -build/} doc{INSTALL README} legal{COPYRIGHT} manifest

# Don't install tests or the INSTALL file.
#
tests/:          install = false
doc{INSTALL}@./: install = false
